# docker compose file defininf simple echo server with haproxy in front
# haproxy is listening on port 80 and 443

version: '3.7'
services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    #ports:
    #  - "8080:8080"
    volumes:
      - ./conf/acquis.yaml:/etc/crowdsec/acquis.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DISABLE_PARSERS: "crowdsecurity/whitelists"
      COLLECTIONS: crowdsecurity/nginx
      DISABLE_ONLINE_API: "true"
      BOUNCER_KEY_haproxy: 6b71a77194327e3bf00bcef884d2688c
    depends_on:
      - nginx-server
  nginx-server:
    image: nginx:latest
    #ports:
    #  - "8081:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
  haproxy:
    depends_on:
      - nginx-server
      - crowdsec
    image: haproxy:latest
    ports:
      - 80:80
    volumes:
      - ./conf/haproxy_local.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ../lib:/usr/local/crowdsec/lua/haproxy/
      - ../templates:/var/lib/crowdsec/lua/haproxy
      - ../community_blocklist.map:/var/lib/crowdsec/lua/haproxy/community_blocklist.map
      - ./conf/crowdsec-haproxy-bouncer.conf:/usr/local/crowdsec/crowdsec-haproxy-bouncer.conf